
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 27 00:11:19 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 18;
  public static final int NE = 22;
  public static final int LT = 19;
  public static final int SEMICOLON = 11;
  public static final int SELECT = 14;
  public static final int OR = 17;
  public static final int CHAR = 7;
  public static final int LEFTPAR = 25;
  public static final int END = 9;
  public static final int INTCONST = 27;
  public static final int RIGHTPAR = 26;
  public static final int GT = 23;
  public static final int COLON = 10;
  public static final int ID = 28;
  public static final int LE = 20;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 8;
  public static final int BOOLEAN = 5;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int CHARCONST = 30;
  public static final int REALCONST = 29;
  public static final int GE = 24;
  public static final int CASE = 15;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int ARROW = 16;
  public static final int EQ = 21;
  public static final int ASSIGN = 13;
  public static final int INTEGER = 4;
  public static final int REAL = 6;
  public static final int BOOLCONST = 31;
}

