
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 26 16:40:25 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 14;
  public static final int NE = 18;
  public static final int LT = 15;
  public static final int SEMICOLON = 7;
  public static final int SELECT = 10;
  public static final int OR = 13;
  public static final int LEFTPAR = 22;
  public static final int END = 5;
  public static final int INTCONST = 24;
  public static final int RIGHTPAR = 23;
  public static final int GT = 19;
  public static final int COLON = 6;
  public static final int ID = 25;
  public static final int LE = 16;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 4;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int CHARCONST = 27;
  public static final int REALCONST = 26;
  public static final int GE = 20;
  public static final int CONST = 21;
  public static final int CASE = 11;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int ARROW = 12;
  public static final int EQ = 17;
  public static final int ASSIGN = 9;
  public static final int BOOLCONST = 28;
}

