
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 17 02:10:55 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 19;
  public static final int NE = 23;
  public static final int LT = 20;
  public static final int SEMICOLON = 7;
  public static final int SELECT = 15;
  public static final int OR = 18;
  public static final int CHAR = 11;
  public static final int LEFTPAR = 27;
  public static final int END = 5;
  public static final int RIGHTPAR = 28;
  public static final int GT = 24;
  public static final int COLON = 6;
  public static final int LE = 21;
  public static final int ID = 9;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 4;
  public static final int BOOLEAN = 13;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int GE = 25;
  public static final int CONST = 26;
  public static final int ARROW = 17;
  public static final int CASE = 16;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int EQ = 22;
  public static final int ASSIGN = 14;
  public static final int INTEGER = 10;
  public static final int REAL = 12;
}

